### ISSUE TITLE
XDebug manual initiation

### ISSUE THREAD

**Issue by anthonysan95** [wardenenv/images#16]
Could you please add the check in the nginx default.conf map for xdebug manual initiation parameters? (https://xdebug.org/docs/step_debug#manual-init)
Either $arg_XDEBUG_SESSION or $arg_XDEBUG_SESSION_START is fine.

I've got a case where I need to debug but I can't set the cookie.
Thanks.

**Comment by navarr** [comment]
I've added this feature in 071f89b, which will be building shortly.
