### ISSUE TITLE
Blackfire Image / Probe Outdated

### ISSUE THREAD

**Issue by sprankhub** [wardenenv/images#36]
This is similar to #14.

Again, Blackfire says it uses an old version 1.92.15 of the probe. According to https://docs.blackfire.io/up-and-running/update, it should be 1.92.23. Looks like it is not updated automatically...?

**Comment by sprankhub** [comment]
I'm sorry, I fear that was my bad. I pulled, but I pulled before enabling Blackfire :facepalm: Never mind!

**Comment by navarr** [comment]
Ty!
